In [1]:
import torch

# Creating Tensor

In [2]:
# helper function
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

# create tensor of zeros
describe(torch.zeros(2,3))

# create tensor of random
# in uniform distrubution
describe(torch.rand(2,3))
# in normal distribution
describe(torch.randn(2,3))

# tensor with defined values
x = torch.rand(2,3)
describe(x)
# fill with 3 values
x.fill_(3)
describe(x)

# tensor from list
y = torch.Tensor([[1,2,3],
                [4,5,6]])
describe(y)

# torch from numpy
import numpy as np
z = np.random.rand(2,3)
describe(torch.from_numpy(z))

# defining the data types
a = torch.FloatTensor([1,2,3])
describe(a)
# convert data types
a = a.long()
describe(a)

# from list with data type
b = torch.tensor([1,2,3], dtype=torch.int64)
describe(b)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7881, 0.9644, 0.3926],
        [0.9942, 0.4940, 0.1118]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.5601,  0.8279,  1.1155],
        [-0.5231, -0.7402,  0.1025]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.8446, 0.8319, 0.9789],
        [0.3468, 0.0131, 0.8573]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[3., 3., 3.],
        [3., 3., 3.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.3110, 0.8406, 0.9588],
        [0.0692, 0.6474, 0.0811]], dtype=torch.float64)
Type: torch.FloatTensor
Shape/size: torch.Size([3])
Values: 
tensor([1., 2., 3.])
Type: torch.LongTensor
Shape/si

# Tensor Operations

In [3]:
# use arithmetic operators
describe(x + y)
# or use methods
describe(torch.add(a , b))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[4., 5., 6.],
        [7., 8., 9.]])
Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([2, 4, 6])


In [4]:
# represent tensor in other dimension
x = torch.arange(16)
describe(x)
x = x.view(2,8)
describe(x.view(2,8))

Type: torch.LongTensor
Shape/size: torch.Size([16])
Values: 
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
Type: torch.LongTensor
Shape/size: torch.Size([2, 8])
Values: 
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])


In [5]:
# slicing tensors
describe(x[1, :5])

Type: torch.LongTensor
Shape/size: torch.Size([5])
Values: 
tensor([ 8,  9, 10, 11, 12])


In [6]:
# complex indexing
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 0,  2],
        [ 8, 10]])


In [7]:
# concatenating tensors
describe(torch.cat([x,x], dim=0))
describe(torch.cat([x,x], dim=1))
describe(torch.stack([x,x]))

Type: torch.LongTensor
Shape/size: torch.Size([4, 8])
Values: 
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 16])
Values: 
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 8])
Values: 
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]],

        [[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]]])


In [8]:
# tensor multiplication
x1 = torch.rand(3,5)
x2 = torch.rand(5,1)
describe(torch.mm(x1,x2))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[1.1552],
        [1.3060],
        [1.6776]])


In [9]:
# creating tensors for gradient bookeeping
x = torch.ones(2,2, requires_grad=True)
print(x.grad is None)

y = (x + 2) * (x + 5) + 3
print(x.grad is None)

z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

True
True
Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


## Cuda Tensors

In [10]:
print(torch.cuda.is_available())

True


In [11]:
# method to detect cuda availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [12]:
# create tensor of x and give it
# to device in this case cuda
x = torch.rand(3,3).to(device)
describe(x)

# cannot operate the tensor on different
# device

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.2228, 0.7055, 0.4441],
        [0.0451, 0.0261, 0.8816],
        [0.9844, 0.7162, 0.2607]], device='cuda:0')


# Exercices

In [4]:
# create a 2D tensor and add a dimension of size 1 at dimension 0
a = torch.rand(2,3)
describe(a)
describe(a.unsqueeze(0))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5575, 0.9103, 0.4351],
        [0.2068, 0.4203, 0.1948]])
Type: torch.FloatTensor
Shape/size: torch.Size([1, 2, 3])
Values: 
tensor([[[0.5575, 0.9103, 0.4351],
         [0.2068, 0.4203, 0.1948]]])


In [5]:
# remove the extra dimension on previous q
describe(a.squeeze(0))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5575, 0.9103, 0.4351],
        [0.2068, 0.4203, 0.1948]])


In [6]:
# create random tensor shape of size 5x3
# with elements in range [3,7)
describe(3 + torch.rand(5, 3) * (7 - 3))

Type: torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[3.5978, 3.8723, 4.8034],
        [4.6410, 5.3655, 3.7163],
        [5.4637, 3.8232, 3.6808],
        [5.5894, 4.6125, 4.1187],
        [6.3006, 3.0961, 3.6242]])


In [8]:
# create tensor whitin values in 
# normal distribution mean = 0, std = 1
describe(torch.randn(3,4).normal_(mean=0, std=1))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0.4263, -1.3045, -0.3604,  0.6159],
        [-0.4132, -0.1978,  1.7153, -0.1627],
        [-0.0791,  0.1943, -0.8497, -0.9871]])


In [15]:
# retrieve all of non zero elements in tensor
# [1,1,1,0,1]
b = torch.tensor([1,1,1,0,1])
describe(b.nonzero())
# show all of non zero number
# using indexing from nonzero
indexing = torch.flatten(b.nonzero(), start_dim=0, end_dim=-1)
describe(indexing)
describe(torch.index_select(b, dim=0, index=indexing))

Type: torch.LongTensor
Shape/size: torch.Size([4, 1])
Values: 
tensor([[0],
        [1],
        [2],
        [4]])
Type: torch.LongTensor
Shape/size: torch.Size([4])
Values: 
tensor([0, 1, 2, 4])
Type: torch.LongTensor
Shape/size: torch.Size([4])
Values: 
tensor([1, 1, 1, 1])


In [18]:
# create random tensor with size of 3x1
# and stack four copies
c = torch.rand(3,1)
describe(c.expand(3,4))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.3879, 0.3879, 0.3879, 0.3879],
        [0.3722, 0.3722, 0.3722, 0.3722],
        [0.5368, 0.5368, 0.5368, 0.5368]])


In [19]:
# return a batch matrix product
describe(torch.bmm(torch.rand(3,4,5), torch.rand(3,5,4)))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[0.7523, 0.9580, 1.1763, 0.8556],
         [1.7624, 1.3639, 2.1123, 1.1101],
         [0.6728, 0.6501, 0.6979, 0.1987],
         [0.5132, 0.4503, 1.0062, 0.2493]],

        [[1.7245, 1.1006, 0.5768, 1.4180],
         [2.5873, 1.9901, 1.3462, 2.0930],
         [2.5803, 1.8404, 1.2517, 2.2748],
         [2.3777, 1.7282, 0.9221, 2.1412]],

        [[1.0788, 1.6280, 0.9792, 1.4255],
         [1.0153, 1.4417, 0.8747, 1.3454],
         [1.3644, 2.1280, 1.4497, 1.5997],
         [0.9229, 2.0063, 1.0009, 1.2392]]])


In [20]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
describe(torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size())))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.0759, 1.6159, 1.4433, 1.4911],
         [0.4393, 1.1666, 0.9750, 0.9905],
         [0.4820, 1.2388, 1.2895, 0.6734],
         [0.3791, 0.6059, 0.7261, 0.7058]],

        [[0.5924, 1.1555, 0.9336, 1.0651],
         [1.3226, 2.1451, 1.9133, 2.3243],
         [0.8404, 1.5608, 1.2237, 1.3766],
         [0.8705, 1.3436, 1.2705, 1.7210]],

        [[1.3882, 2.3121, 2.2154, 2.0088],
         [0.3879, 0.5884, 0.4690, 0.5461],
         [0.7500, 1.6071, 1.1777, 1.6645],
         [1.1028, 1.8185, 1.7481, 1.6057]]])


In [22]:
print(b.size())

torch.Size([5, 4])
